flowchart TD
    U[User signs in] --> ACC[Account]
    ACC --> ORG{Pick Organization<br/>left-rail bubble}
    ORG --> SPC{Pick Space<br/>sidebar}
    SPC --> COL[Open Collection]
    COL --> GRP[Open Group<br/>optional]
    COL --> IT1[Click Item -> opens URL in new tab]
    GRP --> IT2[Click Item -> opens URL in new tab]
    COL -. share .-> SHR[/t/{slug} public viewer/]
    GRP -. share .-> SHR
    IT1 -. share .-> SHR
